### ISSUE TITLE
rounding of pixel size XY

### ISSUE THREAD

**Issue by manerotoni** [embl-cba/fiji-plugin-cats#12]
For some images generated using ZEN-blue (czi format) one gets the message 

`Error: Image calibration in x and y is not the same; currently cannot take this in to account`

When I look at the metadata of the file the pixel size in X and Y are different but due to floating errors.  
PhysicalSizeX="0.152364193667916" 
PhysicalSizeY="0.15236419366791598" 

 May be you can round up to 9-10 digits (even 3-4 is enough), this should do the job.

**Comment by tischi** [comment]
Good point! Fixed.
Should work now.
