### ISSUE TITLE
Labels look wrong when reviewing

### ISSUE THREAD

**Issue by davodogster** [embl-cba/fiji-plugin-cats#16]
When I review some of the labels they are a really strange shape as shown below, and the line width is thicker than it showed when annotating,

![image](https://user-images.githubusercontent.com/46079516/59095796-78a48800-896d-11e9-9979-fd8ad8fa805c.png)

**Comment by tischi** [comment]
This is normal!
I just display them thicker such that they are easier to see. 
But it is just a display thing.
Do you think this is confusing? I could remove this.

**Comment by davodogster** [comment]
Yes it's a little confusing, especially if you don't know that it's just a display thing.

**Comment by tischi** [comment]
Ok. will work on it!

**Comment by tischi** [comment]
There is a UI asking the user to specify the stroke width during the review.
I changed the default to 1 (it was 4).
